version: "3"

services: 
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
    ports:
      - "3307:3306"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local